# Generated by Django 2.2.6 on 2019-10-28 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('tech', models.TextField(default='None', max_length=10000, null=True)),
                ('lang', models.CharField(default='None', max_length=10000, null=True)),
                ('phone', models.CharField(default='None', max_length=50, null=True)),
                ('link', models.CharField(default='None', max_length=5000000, null=True)),
                ('skills', models.TextField(default='None', max_length=5000000, null=True)),
                ('sem', models.CharField(default='None', max_length=50, null=True)),
                ('book', models.ManyToManyField(blank=True, related_name='book', to=settings.AUTH_USER_MODEL)),
                ('lkes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
