# Generated by Django 2.2.6 on 2019-10-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkin',
            field=models.CharField(default='None', max_length=5000000, null=True),
        ),
    ]
