# Generated by Django 2.2.6 on 2019-10-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0002_profile_linkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='linkin',
            field=models.URLField(blank=True, db_index=True, default='', max_length=128, unique=True, verbose_name='nothing'),
        ),
    ]
