# Generated by Django 2.2.6 on 2019-10-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0003_auto_20191028_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='link',
            field=models.URLField(blank=True, db_index=True, default='', max_length=128, unique=True, verbose_name='nothing'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sem',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
