# Generated by Django 2.2.6 on 2019-10-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0004_auto_20191029_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='link',
            field=models.URLField(blank=True, db_index=True, default='', max_length=128, unique=True, verbose_name='nothingss'),
        ),
    ]
