# Generated by Django 2.2.6 on 2019-10-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0005_auto_20191029_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='link',
            field=models.CharField(default='', max_length=5000000, null=True),
        ),
    ]
