# Generated by Django 2.2.6 on 2019-10-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0006_auto_20191029_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='linkin',
            field=models.CharField(default='', max_length=5000000, null=True),
        ),
    ]
