# Generated by Django 2.2.6 on 2019-11-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0007_auto_20191029_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stop',
            field=models.CharField(default='', max_length=5000000, null=True),
        ),
    ]
