# Generated by Django 2.2.6 on 2019-12-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0008_profile_stop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('to', models.CharField(max_length=50)),
                ('froms', models.CharField(max_length=50)),
                ('read', models.IntegerField(default=0)),
                ('message', models.TextField(max_length=10000)),
            ],
        ),
    ]
